apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  annotations:
    jenkins.io/chart: repositories
  generation: 3
  labels:
    jenkins.io/chart-release: repos
    jenkins.io/namespace: jx
    jenkins.io/version: "1"
    owner: majuansari
    provider: github
    repository: app
  name: majuansari-app
  namespace: jx
  resourceVersion: "2310288"
  selfLink: /apis/jenkins.io/v1/namespaces/jx/sourcerepositories/majuansari-app
  uid: 79772ceb-c0ec-4f08-819f-d55bd5442380
spec:
  description: Imported application for majuansari/app
  httpCloneURL: https://github.com/majuansari/app.git
  org: majuansari
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: app
  scheduler:
    kind: ""
    name: sit-scheduler
  url: https://github.com/majuansari/app.git