apiVersion: jenkins.io/v1
kind: Environment
metadata:
  generation: 1
  name: test
  namespace: jx
spec:
  kind: Permanent
  label: Test
  namespace: jx-test
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  source:
    ref: master
    url: https://github.com/majuansari/environment-jx-aks-test.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
status: {}