apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: majuansari
    provider: github
    repository: jx-gov2
  name: majuansari-jx-gov2
spec:
  description: Imported application for majuansari/jx-gov2
  httpCloneURL: https://github.com/majuansari/jx-gov2.git
  org: majuansari
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx-gov2
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/majuansari/jx-gov2.git
